/* Dynamic business configuration. No fake records are created here. */
window.NAJAH_ACTIVITY_CONFIG = {
  clothing: { label: 'محل ملابس', products: 'الملابس والأصناف', inventory: 'مخزون الملابس', purchase: 'مشتريات الملابس', reports: 'تقارير المبيعات والمقاسات', fields: ['size','color','gender','brand','fabric','season','style'], units: ['قطعة','طقم'], variants: ['size','color'] },
  shoes: { label: 'محل أحذية', products: 'الأحذية والأصناف', inventory: 'مخزون الأحذية', purchase: 'مشتريات الأحذية', reports: 'تقارير المقاسات والمبيعات', fields: ['size','color','gender','brand','material','style'], units: ['زوج','قطعة'], variants: ['size','color'] },
  homeware: { label: 'محل أواني منزلية', products: 'الأواني والأصناف', inventory: 'مخزون الأواني', purchase: 'مشتريات الأواني', reports: 'تقارير الأواني والأطقم', fields: ['product_type','material','size','color','brand','pieces','set','weight'], units: ['قطعة','طقم','كرتون'], variants: ['size','color'] },
  cosmetics: { label: 'مستحضرات تجميل', products: 'المستحضرات والأصناف', inventory: 'مخزون المستحضرات', purchase: 'مشتريات المستحضرات', reports: 'تقارير العلامات والصلاحية', fields: ['brand','category','shade','size','batch_number','expiry_date'], units: ['قطعة','عبوة','كرتون'], variants: ['shade','size'] },
  grocery: { label: 'بقالة / مواد غذائية', products: 'المواد الغذائية', inventory: 'مخزون المواد الغذائية', purchase: 'مشتريات المواد الغذائية', reports: 'تقارير الأصناف والصلاحية', fields: ['unit','weight','pack','carton','expiry_date','batch_number'], units: ['قطعة','كجم','جرام','لتر','مل','عبوة','كرتون'], variants: [] },
  supermarket: { label: 'سوبر ماركت', products: 'أصناف السوبر ماركت', inventory: 'مخزون السوبر ماركت', purchase: 'مشتريات السوبر ماركت', reports: 'تقارير الأقسام والمبيعات', fields: ['unit','weight','pack','carton','expiry_date','batch_number'], units: ['قطعة','كجم','جرام','لتر','مل','عبوة','كرتون'], variants: [] },
  building_materials: { label: 'محل مواد بناء', products: 'مواد البناء', inventory: 'مخزون مواد البناء', purchase: 'مشتريات مواد البناء', reports: 'تقارير الوحدات والكميات', fields: ['material_type','unit','weight','length','width','height','brand'], units: ['قطعة','متر','متر مربع','متر مكعب','كجم','طن','كيس','كرتون'], variants: [] },
  electrical: { label: 'أجهزة كهربائية', products: 'الأجهزة الكهربائية', inventory: 'مخزون الأجهزة والضمان', purchase: 'مشتريات الأجهزة', reports: 'تقارير الضمان والأرقام التسلسلية', fields: ['brand','model','serial_number','warranty_period','warranty_start','warranty_end','voltage','power','color'], units: ['قطعة','كرتون'], variants: ['color'], serialized: true },
  electronics: { label: 'محل إلكترونيات', products: 'الإلكترونيات', inventory: 'مخزون الإلكترونيات', purchase: 'مشتريات الإلكترونيات', reports: 'تقارير الموديلات والضمان', fields: ['brand','model','storage','ram','color','serial_number','warranty'], units: ['قطعة','كرتون'], variants: ['storage','ram','color'], serialized: true },
  mobile: { label: 'هواتف وإكسسوارات', products: 'الهواتف والإكسسوارات', inventory: 'مخزون الهواتف وIMEI', purchase: 'مشتريات الهواتف', reports: 'تقارير IMEI والضمان', fields: ['brand','model','storage','ram','color','imei','serial_number','warranty'], units: ['جهاز','قطعة','كرتون'], variants: ['storage','ram','color'], serialized: true },
  furniture: { label: 'محل أثاث', products: 'الأثاث والأصناف', inventory: 'مخزون الأثاث', purchase: 'مشتريات الأثاث', reports: 'تقارير الموديلات والأبعاد', fields: ['product_type','material','color','dimensions','brand','supplier'], units: ['قطعة','طقم','كرتون'], variants: ['color','dimensions'] },
  home_furnishings: { label: 'مفروشات منزلية', products: 'المفروشات والأصناف', inventory: 'مخزون المفروشات', purchase: 'مشتريات المفروشات', reports: 'تقارير المقاسات والألوان', fields: ['type','size','color','material','pattern','brand'], units: ['قطعة','متر','طقم','كرتون'], variants: ['size','color'] },
  hardware: { label: 'العدد والأدوات', products: 'العدد والأدوات', inventory: 'مخزون العدد والأدوات', purchase: 'مشتريات العدد والأدوات', reports: 'تقارير الأدوات والماركات', fields: ['tool_type','material','size','brand','supplier'], units: ['قطعة','طقم','علبة','كرتون'], variants: [] },
  stationery: { label: 'مكتبة وقرطاسية', products: 'الكتب والقرطاسية', inventory: 'مخزون المكتبة', purchase: 'مشتريات المكتبة', reports: 'تقارير الكتب والقرطاسية', fields: ['category','brand','grade','color'], units: ['قطعة','علبة','كرتون'], variants: ['color'] },
  perfume: { label: 'محل عطور', products: 'العطور والأصناف', inventory: 'مخزون العطور', purchase: 'مشتريات العطور', reports: 'تقارير العطور والماركات', fields: ['brand','fragrance_family','size','batch_number','expiry_date'], units: ['زجاجة','عبوة','كرتون'], variants: ['size'] },
  pharmacy: { label: 'صيدلية / مستلزمات طبية', products: 'الأدوية والمستلزمات الطبية', inventory: 'مخزون الأدوية والصلاحية', purchase: 'المشتريات الدوائية', reports: 'تقارير الأدوية والصلاحية', fields: ['scientific_name','dosage','form','manufacturer','batch_number','expiry_date','prescription_required','supplier'], units: ['قرص','علبة','زجاجة','أنبوب','حقنة','كرتون'], variants: ['dosage','form','batch_number'], expiryTracking: true },
  spare_parts: { label: 'محل قطع غيار', products: 'قطع الغيار', inventory: 'مخزون قطع الغيار', purchase: 'مشتريات قطع الغيار', reports: 'تقارير الموديلات والتوافق', fields: ['part_number','brand','model','vehicle','year','serial_number'], units: ['قطعة','طقم','كرتون'], variants: [] },
  car_accessories: { label: 'إكسسوارات سيارات', products: 'إكسسوارات السيارات', inventory: 'مخزون إكسسوارات السيارات', purchase: 'مشتريات إكسسوارات السيارات', reports: 'تقارير السيارات والموديلات', fields: ['accessory_type','brand','model','color','vehicle'], units: ['قطعة','طقم','كرتون'], variants: ['color'] },
  general: { label: 'تجارة عامة', products: 'المنتجات', inventory: 'المخزون', purchase: 'المشتريات', reports: 'التقارير العامة', fields: ['brand','model','color','size','batch_number','expiry_date'], units: ['قطعة','عبوة','كرتون'], variants: [] },
  other: { label: 'نشاط آخر', products: 'المنتجات', inventory: 'المخزون', purchase: 'المشتريات', reports: 'التقارير', fields: ['brand','model','color','size'], units: ['قطعة','عبوة','كرتون'], variants: [] }
};

window.NAJAH_FIELD_LABELS = {
  size: 'المقاس', color: 'اللون', gender: 'الجنس', brand: 'الماركة', fabric: 'الخامة', season: 'الموسم', style: 'الموديل / الأسلوب',
  product_type: 'نوع المنتج', material: 'المادة', pieces: 'عدد القطع', set: 'طقم أم قطعة', weight: 'الوزن', category: 'التصنيف', shade: 'الدرجة / اللون',
  batch_number: 'رقم التشغيلة', expiry_date: 'تاريخ الانتهاء', unit: 'الوحدة', pack: 'العبوة', carton: 'الكرتون',
  material_type: 'نوع المادة', length: 'الطول', width: 'العرض', height: 'الارتفاع', model: 'الموديل', serial_number: 'الرقم التسلسلي',
  warranty_period: 'مدة الضمان', warranty_start: 'بداية الضمان', warranty_end: 'نهاية الضمان', voltage: 'الجهد الكهربائي', power: 'القدرة',
  storage: 'سعة التخزين', ram: 'الذاكرة RAM', imei: 'IMEI', warranty: 'الضمان', type: 'النوع', pattern: 'النقشة',
  tool_type: 'نوع الأداة', grade: 'المرحلة / الدرجة', fragrance_family: 'عائلة العطر', scientific_name: 'الاسم العلمي', dosage: 'الجرعة / التركيز',
  form: 'الشكل الدوائي', manufacturer: 'الشركة المصنعة', prescription_required: 'يتطلب وصفة', supplier: 'المورد', part_number: 'رقم القطعة',
  vehicle: 'المركبة / الموديل', year: 'السنة', accessory_type: 'نوع الإكسسوار', dimensions: 'الأبعاد'
};
